spring:
  application:
    name: parking

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Notification configuration
notification:
  scheduler:
    processScheduled:
      delayMs: 60000  # 1 minute
    retryFailed:
      delayMs: 300000  # 5 minutes
  retention:
    days: 30
  channels:
    email:
      enabled: true
      provider: "mock"  # Change to actual provider (sendgrid, aws-ses, etc.)
    sms:
      enabled: true
      provider: "mock"  # Change to actual provider (twilio, aws-sns, etc.)
    push:
      enabled: true
      provider: "mock"  # Change to actual provider (firebase, aws-sns, etc.)
    in-app:
      enabled: true
      retention-days: 30

jwt:
  secret: "${JWT_SECRET}"
  expiration: 3600 # 1 hour
  refresh-expiration: 2592000 # 30 days

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    operations-sorter: method
    url: /v3/api-docs


